CODE_SNIPPETS: list[str] = [
    "def hello(name): return f'Hello, {name}!'",
    "const sum = (a, b) => a + b;",
    "if err != nil { return err }",
    "print([x**2 for x in range(10)])",
    "const [state, setState] = useState(null);",
    "func main() { fmt.Println(\"hello\") }",
    "export default function App() { return <div />; }",
    "arr.filter(x => x !== null).map(x => x.id)",
    "with open('file.txt', 'r') as f: data = f.read()",
    "SELECT * FROM users WHERE active = true;",
    "impl Display for Point { fn fmt(&self) -> Result {} }",
    "const result = await fetch('/api/data').then(r => r.json());",
    "lambda x, y: x if x > y else y",
    "type Props = { name: string; age?: number };",
    "fn main() { let v: Vec<i32> = vec![1, 2, 3]; }",
    "Object.keys(obj).forEach(key => console.log(key));",
    "class Meta(type): def __new__(cls, name, bases, dct): ...",
    "router.get('/users/:id', async (req, res) => { });",
    "match value { Some(x) => x, None => 0 }",
    "from collections import defaultdict, Counter",
    "interface User { id: number; email: string; }",
    "go func() { ch <- processData(input) }()",
    "assert response.status_code == 200",
    "docker run -d -p 8080:80 --name app nginx:latest",
    "git rebase -i HEAD~3 && git push --force-with-lease",
    "kubectl get pods -n production -o wide",
    "chmod 755 deploy.sh && ./deploy.sh --env=prod",
    "tar -czf backup.tar.gz /var/data/ --exclude='*.log'",
    "awk '{print $1, $NF}' access.log | sort | uniq -c",
    "find . -name '*.py' -exec grep -l 'TODO' {} \\;",
    "sed -i 's/old_func/new_func/g' src/*.py",
    "curl -X POST -H 'Content-Type: application/json' -d '{}'",
]

PARAGRAPHS: list[str] = [
    "The quick brown fox jumps over the lazy dog while the cat sleeps peacefully on the warm windowsill nearby.",
    "Programming is the art of telling another human what one wants the computer to do. Code is read far more often than it is written.",
    "In the beginning was the command line. Before windows and mice, there were terminals and keyboards and the soft glow of green phosphor.",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
    "The best error message is the one that never shows up. Design your systems to prevent errors rather than just reporting them.",
    "Simplicity is prerequisite for reliability. Complex systems break in complex ways that are difficult to predict or debug.",
    "First solve the problem. Then write the code. Too many engineers jump straight to implementation without understanding the domain.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "The most dangerous phrase in the language is we have always done it this way. Question assumptions and challenge conventions.",
    "Software is like entropy. It is difficult to grasp, weighs nothing, and obeys the second law of thermodynamics: it always increases.",
    "There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors.",
    "A language that does not affect the way you think about programming is not worth knowing. Learn broadly and apply wisely.",
]
